galaxy_info:
  author: Vladimir Grushevsky
  description: Backup databases
  company: PAPALAM.ru

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: "2.1"

  platforms:
  - name: Ubuntu
    versions:
    - all

  galaxy_tags: []

dependencies: []
